/~/.ssh/email@guinetik.com# ~/.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Initialize zoxide (smarter cd command)
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
fi

# Source shared aliases
if [ -f "$HOME/.config/shell/aliases.sh" ]; then
    source "$HOME/.config/shell/aliases.sh"
fi

# Enable starship prompt
if command -v starship &> /dev/null; then
  eval "$(starship init bash)"
fi

# ---- Atuin (shell history management) ----
# Atuin provides enhanced shell history with sync, search, and statistics
# Ctrl+R: Open atuin fuzzy history search
if command -v atuin &> /dev/null; then
  eval "$(atuin init bash)"
fi

# Enable color support
export TERM=xterm-256color

# Set editor
export EDITOR=nano

# Jabba (Java Version Manager)
[ -s "/root/.jabba/jabba.sh" ] && source "/root/.jabba/jabba.sh"
export JABBA_HOME="$HOME/.jabba"
[ -s "$JABBA_HOME/jabba.sh" ] && source "$JABBA_HOME/jabba.sh"
# Maven Daemon (mvnd)
export MVND_HOME="/root/.mvnd/maven-mvnd-1.0.2-linux-amd64"
export PATH="$MVND_HOME/bin:$PATH"

# pyenv setup
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# Guinetik backend configuration is managed by install_guinetik.sh
# Run: ~/gui-dotfiles/common/install_guinetik.sh to configure
# BEGIN GUINETIK CONFIG
# Guinetik Backend Configuration
# Generated by install_guinetik.sh

# Project root directory
export GUINETIK_ROOT="/mnt/d/Developer/guinetik-backend"

# Docker compose command
export DOCKERC="docker compose"

# Server connection details
export GUINETIK_SERVER="45.32.174.122"
export GUINETIK_KEY="/home/guinetik/.ssh/email@guinetik.com"

# API credentials
export GUINETIK_LOGIN="agents@guinetik.com"
export GUINETIK_PASSWORD="CCw7gI4Vwm6utc"
export GUINETIK_API_URL="https://api.guinetik.com"

# Bitwarden Secrets Manager token
export BWS_ACCESS_TOKEN="0.b6b3e709-6a95-42dc-8fd8-b36c0078dc60.JVOjV0v9CAAHDDNcV9wynr6iZo8RpX:FJj/X6sYYth7/xlSr16nag=="

# API token (generated at runtime by guinetik-login)
export GUINETIK_API_TOKEN=""

# SSH helper function
guinetikssh() {
    if [ -n "$1" ]; then
        ssh -i "$GUINETIK_KEY" "root@$GUINETIK_SERVER" "$@"
    else
        ssh -i "$GUINETIK_KEY" "root@$GUINETIK_SERVER"
    fi
}
alias guinetikssh="guinetikssh"

# API login function
guinetik-login() {
  if [[ -z "$GUINETIK_LOGIN" || -z "$GUINETIK_PASSWORD" || -z "$GUINETIK_API_URL" ]]; then
    echo "⚠️  Missing one or more required environment variables:"
    echo "    GUINETIK_LOGIN, GUINETIK_PASSWORD, GUINETIK_API_URL"
    return 1
  fi

  local response token
  response=$(curl -s -X POST "$GUINETIK_API_URL/auth/login-email" \
    -H "Content-Type: application/json" \
    -d "{\\email\\:\"$GUINETIK_LOGIN\\,\\password\\:\"$GUINETIK_PASSWORD\\}")

  token=$(echo "$response" | jq -r '.token // empty')

  if [[ -n "$token" ]]; then
    export GUINETIK_API_TOKEN="$token"
    echo "✅ Login successful. Token saved to \$GUINETIK_API_TOKEN"
  else
    echo "❌ Login failed."
    echo "$response"
    return 1
  fi
}

alias guinetikapi="guinetik-login"
# END GUINETIK CONFIG
. "$HOME/.cargo/env"
source "$HOME/.cargo/env"
